**Dictionary**





*   Dictionary is a mutable data type in Python.
*   A python dictionary is a collection of key and value pairs separated by a colon (:) & enclosed in curly braces {}.
*   Keys must be unique in a dictionary, duplicate values are allowed.

![Screenshot 2025-09-24 140711.png]()

**Create Dictionary**

In [17]:
mydict = dict() # empty dictionary
mydict

{}

In [18]:
mydict = {} # empty dictionary
mydict

{}

In [19]:
mydict = {1:'one' , 2:'two' , 3:'three'} # dictionary with integer keys
mydict

{1: 'one', 2: 'two', 3: 'three'}

In [20]:
mydict = dict({1:'one' , 2:'two' , 3:'three'}) # Create dictionary using dict()
mydict

{1: 'one', 2: 'two', 3: 'three'}

In [21]:
mydict = {'A':'one' , 'B':'two' , 'C':'three'} # dictionary with character keys
mydict

{'A': 'one', 'B': 'two', 'C': 'three'}

In [22]:
mydict = {1:'one' , 'A':'two' , 3:'three'} # dictionary with mixed keys
mydict

{1: 'one', 'A': 'two', 3: 'three'}

In [23]:
mydict.keys() # Return Dictionary Keys using keys() method

dict_keys([1, 'A', 3])

In [24]:
mydict.values() # Return Dictionary Values using values() method

dict_values(['one', 'two', 'three'])

In [25]:
mydict.items() # Access each key-value pair within a dictionary

dict_items([(1, 'one'), ('A', 'two'), (3, 'three')])

In [26]:
mydict = {1:'one' , 2:'two' , 'A':['asif' , 'john' , 'Maria']} # dictionary with
mydict

{1: 'one', 2: 'two', 'A': ['asif', 'john', 'Maria']}

In [28]:
mydict = {1:'one' , 2:'two' , 'A':['asif' , 'john' , 'Maria'], 'B':('Bat' , 'cat', 'hat')}
mydict

{1: 'one',
 2: 'two',
 'A': ['asif', 'john', 'Maria'],
 'B': ('Bat', 'cat', 'hat')}

In [29]:
keys = {'a' , 'b' , 'c' , 'd'}
mydict3 = dict.fromkeys(keys) # Create a dictionary from a sequence of keys
mydict3

{'d': None, 'a': None, 'b': None, 'c': None}

In [30]:
keys = {'a' , 'b' , 'c' , 'd'}
value = 10
mydict3 = dict.fromkeys(keys , value) # Create a dictionary from a sequence of
mydict3

{'d': 10, 'a': 10, 'b': 10, 'c': 10}

In [31]:
keys = {'a' , 'b' , 'c' , 'd'}
value = [10,20,30]
mydict3 = dict.fromkeys(keys , value) # Create a dictionary from a sequence of
mydict3

{'d': [10, 20, 30], 'a': [10, 20, 30], 'b': [10, 20, 30], 'c': [10, 20, 30]}

In [32]:
value.append(40)
mydict3

{'d': [10, 20, 30, 40],
 'a': [10, 20, 30, 40],
 'b': [10, 20, 30, 40],
 'c': [10, 20, 30, 40]}

**Accessing Items**

In [99]:
mydict = {1:'one' , 2:'two' , 3:'three' , 4:'four'}
mydict

{1: 'one', 2: 'two', 3: 'three', 4: 'four'}

In [100]:
mydict[1] # Access item using key

'one'

In [101]:
mydict.get(1) # Access item using get() method

'one'

In [102]:
mydict1 = {'Name':'Bharti' , 'ID': 74123 , 'DOB': 2003 , 'job' :'Analyst'}
mydict1

{'Name': 'Bharti', 'ID': 74123, 'DOB': 2003, 'job': 'Analyst'}

In [103]:
mydict1['Name'] # Access item using key

'Bharti'

In [104]:
mydict1.get('job') # Access item using get() method

'Analyst'

**Add, Remove & Change Items**

In [89]:
mydict1 = {'Name':'Bharti' , 'ID': 12345 , 'DOB': 2003 , 'Address' : 'Chatrapati Sambhajinagar'}
mydict1

{'Name': 'Bharti',
 'ID': 12345,
 'DOB': 2003,
 'Address': 'Chatrapati Sambhajinagar'}

In [90]:
mydict1['DOB'] = 1992 # Changing Dictionary Items
mydict1['Address'] = 'Delhi'
mydict1

{'Name': 'Bharti', 'ID': 12345, 'DOB': 1992, 'Address': 'Delhi'}

In [91]:
dict1 = {'DOB':1995}
mydict1.update(dict1)
mydict1

{'Name': 'Bharti', 'ID': 12345, 'DOB': 1995, 'Address': 'Delhi'}

In [92]:
mydict1['Job'] = 'Analyst' # Adding items in the dictionary
mydict1

{'Name': 'Bharti',
 'ID': 12345,
 'DOB': 1995,
 'Address': 'Delhi',
 'Job': 'Analyst'}

In [93]:
mydict1.pop('Job') # Removing items in the dictionary using Pop method
mydict1

{'Name': 'Bharti', 'ID': 12345, 'DOB': 1995, 'Address': 'Delhi'}

In [94]:
mydict1.popitem() # A random item is removed

('Address', 'Delhi')

In [95]:
mydict1

{'Name': 'Bharti', 'ID': 12345, 'DOB': 1995}

In [96]:
del[mydict1['ID']] # Removing item using del method
mydict1

{'Name': 'Bharti', 'DOB': 1995}

In [97]:
mydict1.clear() # Delete all items of the dictionary using clear method
mydict1

{}

In [98]:
del mydict1 # Delete the dictionary object
mydict1

NameError: name 'mydict1' is not defined

**Copy Dictionary**

In [80]:
mydict = {'Name':'Bharti' , 'ID': 12345 , 'DOB': 2003 , 'Address' : 'Chatrapati Sambhajinagar'}
mydict

{'Name': 'Bharti',
 'ID': 12345,
 'DOB': 2003,
 'Address': 'Chatrapati Sambhajinagar'}

In [81]:
mydict1 = mydict # Create a new reference "mydict1"

In [82]:
id(mydict) , id(mydict1) # The address of both mydict & mydict1 will be the same

(137741125349056, 137741125349056)

In [83]:
mydict2 = mydict.copy() # Create a copy of the dictionary

In [84]:
id(mydict2) # The address of mydict2 will be different from mydict

137741125351424

In [85]:

mydict['Address'] = 'Mumbai'

In [86]:
mydict

{'Name': 'Bharti', 'ID': 12345, 'DOB': 2003, 'Address': 'Mumbai'}

In [87]:
mydict1 # mydict1 will be also impacted as it is pointing to the same dictionary

{'Name': 'Bharti', 'ID': 12345, 'DOB': 2003, 'Address': 'Mumbai'}

In [88]:
mydict2 # Copy of list won't be impacted due to the changes made in the original

{'Name': 'Bharti',
 'ID': 12345,
 'DOB': 2003,
 'Address': 'Chatrapati Sambhajinagar'}

**Loop through a Dictionary**

In [60]:
mydict1 = {'Name':'Bharti' , 'ID': 12345 , 'DOB': 2003 , 'Address' : 'Chatrapati Sambhajinagar' ,'Job': 'Analyst'}
mydict1

{'Name': 'Bharti',
 'ID': 12345,
 'DOB': 2003,
 'Address': 'Chatrapati Sambhajinagar',
 'Job': 'Analyst'}

In [62]:
for i in mydict1:
  print(i , ':' , mydict1[i]) # Key & value pair

Name : Bharti
ID : 12345
DOB : 2003
Address : Chatrapati Sambhajinagar
Job : Analyst

In [64]:
for i in mydict1:
  print(mydict1[i]) # Dictionary items

Bharti
12345
2003
Chatrapati Sambhajinagar
Analyst

**Dictionary Membership**

In [65]:
mydict1 = {'Name':'Bharti' , 'ID': 12345 , 'DOB': 2003 , 'Address' : 'Chatrapati Sambhajinagar' ,'Job': 'Analyst'}
mydict1

{'Name': 'Bharti',
 'ID': 12345,
 'DOB': 2003,
 'Address': 'Chatrapati Sambhajinagar',
 'Job': 'Analyst'}

In [66]:
'Name' in mydict1 # Test if a key is in a dictionary or not.

True

In [67]:
'Bharti' in mydict1 # Membership test can be only done for keys.

False

In [68]:
'ID' in mydict1

True

In [69]:
'Address' in mydict1

True

**All / Any**

The all() method returns:


*   True - If all all keys of the dictionary are true
*   False - If any key of the dictionary is false

The any() function returns True if any key of the dictionary is True. If not, any() returns False.

In [70]:
mydict1 = {'Name':'Bharti' , 'ID': 12345 , 'DOB': 2003 , 'Address' : 'Chatrapati Sambhajinagar' ,'Job': 'Analyst'}
mydict1

{'Name': 'Bharti',
 'ID': 12345,
 'DOB': 2003,
 'Address': 'Chatrapati Sambhajinagar',
 'Job': 'Analyst'}

In [71]:
all(mydict1) # Will Return false as one value is false (Value 0)

True